# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zht < Formula
  desc " The ZSH History Tool "
  homepage "https://github.com/forquare/zht"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/forquare/zht/releases/download/0.1.1/zht_0.1.1_macOS_all.tar.gz"
    sha256 "67deffdfbcf6f2696a893651068be9096648fbf06b7f862b245fe36e796981d5"

    def install
      bin.install "zht"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forquare/zht/releases/download/0.1.1/zht_0.1.1_Linux_ARM64.tar.gz"
      sha256 "578ece782c3df62aedec3a72dab11da145d51266c745eb905b07ceeb963572e4"

      def install
        bin.install "zht"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forquare/zht/releases/download/0.1.1/zht_0.1.1_Linux_64bit.tar.gz"
      sha256 "b83d06e261f4fe446fc04fc83170b99dc83f40be22b2feb896de697724e6b78c"

      def install
        bin.install "zht"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/forquare/zht/releases/download/0.1.1/zht_0.1.1_Linux_ARMv6.tar.gz"
      sha256 "8f2514e46f3d090070c7cd0690bfccbda3a93c247520866479aeb7157daf53bb"

      def install
        bin.install "zht"
      end
    end
  end
end
