# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zht < Formula
  desc " The ZSH History Tool "
  homepage "https://github.com/forquare/zht"
  version "0.3.0"
  license "MIT"

  on_macos do
    url "https://github.com/forquare/zht/releases/download/0.3.0/zht_macOS_all.tar.gz"
    sha256 "161fa60508b46d6610b83e69be9a13c68b30614ff4f252abaac3d0d7a105b51a"

    def install
      bin.install "zht"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/forquare/zht/releases/download/0.3.0/zht_Linux_64bit.tar.gz"
      sha256 "367e677589042ed8d23ee84c99be9398bf3897d4bd2a88ccec79031033aa56bc"

      def install
        bin.install "zht"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/forquare/zht/releases/download/0.3.0/zht_Linux_ARMv6.tar.gz"
      sha256 "48eb4a74d4f82dd0b52b6e66cfcab168db01a7fe1f0793bcc31973bcbca1b1f4"

      def install
        bin.install "zht"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forquare/zht/releases/download/0.3.0/zht_Linux_ARM64.tar.gz"
      sha256 "bec64a9749e49c442d270ba44155668a40ec68dd0c8a39160e56c9333584b544"

      def install
        bin.install "zht"
      end
    end
  end
end
